id: P92544522
initial_creation_type: input
source_metadata:
  title: Mind Training (Lojong)
  language: en
  description: 'Texts on so-called mind training (blo sbyong), the system of practical
    instructions for developing the compassion and wisdom of bodhicitta:'
  volume:
    1ec72fd1294f4dbd901e309ec6b0cf74:
      title: Seven Points of Training the Mind According to the Great Vehicle
      parent: Seven Points of Mind Training
    5c7a3c459ffb40c7a446043163222b14:
      title: Commentary on the Seven Points
      parent: Seven Points of Mind Training
    6464e91e21754fc1931195905604046e:
      title: Notes on the Seven Points of Mind Training
      parent: Seven Points of Mind Training
    330434f685cf4cafba800ee00ed282bb:
      title: Ambrosia for the Mind
      parent: Seven Points of Mind Training
    a5f254f8fb2d4d7890c017616d47559a:
      title: Eight Verses of Training the Mind
      parent: Eight Verses of Training the Mind
    40a9933fdcd040d59f4d71aabc4962af:
      title: The Thirty-Seven Practices of All the Bodhisattvas
      parent: Thirty-Seven Practices
    61e81db78d9c48598e770b03a46a7738:
      title: 'The Blissful Path to the Ocean of Bodhichitta: A Brief Prayer of Aspiration
        for Mind Training'
      parent: Aspiration Prayers
    bc81327024664a51becedfe04b7251e0:
      title: 'The Excellent Path to Enlightenment: An Aspiration Towards the Mahāyāna
        Mind Training'
      parent: Aspiration Prayers
    11607a35a16b43d3b980c2b7f7b8dcfb:
      title: 'The Finest Jewel: An Aspiration Prayer of Mahāyāna Mind Training'
      parent: Aspiration Prayers
    654dec401da348c989d64903eda3562b:
      title: Aspiration to Generate Bodhicitta, Utterly Pure and Supreme
      parent: Aspiration Prayers
    0abf30c3b1dd410fb8d9516bdae757f0:
      title: The Bodhisattva’s Garland of Jewels
      parent: Lojong (general)
    ad1950b210f0484da759f1d0517709d0:
      title: Turning Suffering & Happiness Into Enlightenment
      parent: Lojong (general)
    a4c22ee6592f4db1b401e66103fcb5b0:
      title: The Sayings of Geshe Langri Tangpa
      parent: Lojong (general)
    f659374057984252a00cd164f60233db:
      title: How to Transform Sickness and Other Circumstances
      parent: Lojong (general)
    79d108a0281f4dff993dae4253ff8319:
      title: Thirty Pieces of Heart Advice
      parent: Lojong (general)
    4616e54df6b5467eb94b4d40c6438018:
      title: Three Principal Aspects of the Path
      parent: Lojong (general)
created_at: '2022-03-01T04:44:49.388031'
last_modified_at: '2022-03-01T04:44:49.388037'
